import { Lilita_One, Alumni_Sans_Pinstripe, Ubuntu } from "next/font/google";
import "./globals.css";

// Shortened names
const lilita = Lilita_One({
  variable: "--font-lilita",
  subsets: ["latin"],
  weight: "400", // default weight
});

const alumni = Alumni_Sans_Pinstripe({
  variable: "--font-alumni",
  subsets: ["latin"],
  weight: "400", // must specify for this font
});

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["400", "700"], // can use multiple weights
});

export const metadata = {
  title: "Mahesh Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lilita.variable} ${alumni.variable} ${ubuntu.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
