import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { GlobalProvider } from "./GlobalContext.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My-Portfolio-Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <meta name="google-site-verification" content="YYLXpVnGVsxdSy2Nl-KVOHB8JM9grUzLQ__Qy55vH0o" />
      <link rel="icon" type="image/svg" href="/logo.svg" />
      <body
        className= {`${geistSans.variable} ${geistMono.variable} antialiased font-sans relative`}
      >
        <GlobalProvider>
        <Navbar />
        {children}
        <Footer />
        </GlobalProvider>
      </body>
    </html>
  );
}
